class syslog_ng::config::fragments {

  $fragments = [
    $::syslog_ng::config_path_source,
    $::syslog_ng::config_path_destination,
    $::syslog_ng::config_path_filter,
    $::syslog_ng::config_path_parser,
    $::syslog_ng::config_path_rewrite,
    $::syslog_ng::config_path_logging,
    $::syslog_ng::config_path_fallback,
  ]

  concat { $fragments:
    ensure => present,
    owner  => 'root',
    group  => 'root',
    mode   => '0644',
    warn   => '# This file is generated by Puppet',
    force  => true,
    notify => Class['syslog_ng::service'],
  }

}
